### ISSUE TITLE
mp4 not generated for some rebuilds

### ISSUE THREAD

**Issue by akhtarkamal1-ed** [createwebinar/bbb-download#9]
Hello

For new recordings of short duration the mp4 is created. 

Did a Rebuild on an existing BBB recording and the mp4 was not generated.

Looked into /var/log/bigbluebutton/download/meetingid.log

Looked liked the log had what FFmpeg was trying to do when converting the recording and here is the error at the end of the log.

bbb_version: 2.1.0
Traceback (most recent call last):
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 288, in <module>
    main()
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 267, in main
    dictionary, length, dims = prepare(bbb_version)
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 183, in prepare
    dictionary, length = extract_timings(bbb_version)
  File "/usr/local/bigbluebutton/core/scripts/post_publish/download.py", line 57, in extract_timings
    temp = float(out_times[len(out_times) - 1])
ValueError: could not convert string to float:

Would appreciate if you could point in the right direction.

**Comment by edunova** [comment]
Hi - I am also facing the same problem

**Comment by sydro** [comment]
You can fix this problem with this patch:

```
diff --git a/src/download.py b/src/download.py
index 2f73e68..77aa654 100644
--- a/src/download.py
+++ b/src/download.py
@@ -54,6 +54,9 @@ def extract_timings(bbb_version):
         in_times = str(image.getAttribute('in')).split(' ')
         out_times = image.getAttribute('out').split(' ')
 
+        if not in_times[len(in_times) - 1] or not out_times[len(out_times) - 1]:
+            continue
+
         temp = float(out_times[len(out_times) - 1])
         if temp > total_length:
             total_length = temp

```

**Comment by rmuzzini** [comment]
or change:
`
temp = float(out_times[len(out_times) - 1])
`

with:

```
try:
      temp = float(out_times[len(out_times) - 1])
 except:
     continue
```
